Gizra/elm-hedley

- src/Company.Elm
- src/User.Elm
> Get the user's company info

- src/App.elm
- src/Event.elm
- src/User.elm
> Add events module

- src/Event.elm
> Add selected property

- elm-package.json
`evancz/start-app` requires elm-effects >= 2
https://github.com/evancz/start-app/blob/master/elm-package.json#L15
> Updating elm-effects

- src/elm/Event.elm
> Making events filter case insensitive

- src/elm/App.elm
- src/elm/Event.elm
- src/elm/Leaflet.elm
- src/elm/Login.elm
- src/elm/User.elm
This is the first step in the way of adding router
> Add Activate page action to App

- src/js/elm-interop.js
> Wait for map div to appear before binding to it

- src/assets/scss/_login.scss
- src/assets/scss/style.scss
- src/elm/Login.elm
- src/index.html
> Theme login form

- src/elm/App.elm
> Allow setting activePage via URL

- package.json
> Upadte gulp-sass package version

- src/assets/scss/_footer.scss
- src/assets/scss/style.scss
- src/elm/App.elm
> Add sticky footer with links to repo

- src/js/elm-interop.js
> Don't fitBounds of map when selecting marker

- src/elm/App.elm
- src/elm/Event.elm
- src/elm/Login.elm
- src/elm/User.elm
Now on event page, selecting an event is reflected in the URL
> Improve route logic, and remove dead code

- .travis.yml
- elm-package.json
- package.json
- src/elm/TestRunner.elm
- src/elm/Tests.elm
PR includes Travis integration
> Add Event.SetCompany unit testing

- src/elm/Login.elm
- src/elm/LoginTest.elm
PR also fixed some indentation.
> Add login error messages

- src/assets/scss/_mixin.scss
- src/assets/scss/style.scss
- src/index.html
#72
@amitaibu Ready for review!
> Fix footer overlay

- src/index.html
#70
@amitaibu Ready for review.
> Fix mobile scaling

- src/assets/scss/_login.scss
- src/assets/scss/_mixin.scss
- src/assets/scss/_page-not-found.scss
- src/assets/scss/style.scss
- src/elm/PageNotFound.elm
> Not found page - design

- src/assets/scss/_article-page.scss
- src/assets/scss/_mixin.scss
- src/assets/scss/style.scss
- src/elm/App.elm
- src/elm/Article.elm
#88
@amitaibu PR is ready.
* Desktop:
* Mobile:
> Design article page

- src/assets/scss/_article-page.scss
#121
@amitaibu ready for review.
> Fix li styling under articles

- src/elm/EventAuthorFilter/View.elm
- src/elm/EventList/View.elm
> Events page change action icon.

- src/elm/App/View.elm
> Add credit to pantheon
